namespace: $GIT_BRANCH
routing:
  domain: $GIT_BRANCH.dev.demo.cxcloud.com
  ingressClass: $INGRESS_CLASS
  lbCert: $LB_CERT
  scheme: $SCHEME
  ssl: false
  rules:
    - path: /commerce
      serviceName: package-commerce
      servicePort: 80
    - path: /
      serviceName: package-frontend
      servicePort: 80
