namespace: $GIT_BRANCH
routing:
  domain: $GIT_BRANCH.dev.demo.cxcloud.com
  ingressClass: $INGRESS_CLASS
  lbCert: $LB_CERT
  scheme: $SCHEME
  ssl: false
  rules:
    - path: /api/commerce
      serviceName: package-commerce
      servicePort: 4003
    - path: /api/content
      serviceName: package-content
      servicePort: 4003
    - path: /api/search
      serviceName: package-search
      servicePort: 4003
    - path: /
      serviceName: package-frontend
      servicePort: 80
